plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - - "@semantic-release/exec"
    - verifyConditionsCmd: "./mvnw -B -ntp clean verify -Drevision=${nextRelease.version} -Pdeploy 1>&2"
      publishCmd: "./mvnw -B -ntp nexus-staging:deploy -Pdeploy 1>&2 "
  - - "@semantic-release/github"
    - assets:
        - path: "./target/*-${nextRelease.version}.jar"
          label: Artifact
    - addReleases: top
