plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "./mvnw -B -ntp clean verify -Drevision=${nextRelease.version}-SNAPSHOT -Pdeploy 1>&2 "
      publishCmd: "./mvnw -B -ntp clean deploy -Drevision=${nextRelease.version} -Pdeploy 1>&2 "
  - - "@semantic-release/github"
    - assets:
        - path:
            - "./target/*-{[0-9].[0-9].[0-9]}.jar"
            - "!./target/original*"
          label: Package
