plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - verifyConditionsCmd: "./mvnw -B -ntp verify -Dgpg.passphrase=$GPG_PASSPHRASE 1>&2"
      publishCmd: "./mvnw -B -ntp deploy -Drevision=${nextRelease.version}"
