plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - verifyConditionsCmd: "./verify.sh"
      publishCmd: "./publish.sh ${nextRelease.version} ${options.branch} ${commits.length} ${Date.now()}"
