plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - verifyConditionsCmd: "./mvnw -B -ntp verify
        -Dgpg.passphrase=$GPG_PASSPHRASE
         -Pdeploy 1>&2"
      publishCmd: "./mvnw -B -ntp deploy
        -Drevision=${nextRelease.version}
        -DskipNexusStagingDeployMojo=true
        -DaltSnapshotDeploymentRepository=snapshots::default::https://oss.sonatype.org/content/repositories/snapshots
        -DaltReleaseDeploymentRepository=releases::default::https://oss.sonatype.org/service/local/staging/deploy/maven2
        -Pdeploy
        -s maven-settings.xml 1>&2"
