plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - - "@semantic-release/exec"
    - verifyConditionsCmd: "./mvnw -B -ntp clean verify -Pdeploy 1>&2 "
      publishCmd: "./mvnw -B -ntp clean deploy -Drevision=${nextRelease.version} -Pdeploy 1>&2 "
  - - "@semantic-release/github"
    - assets:
        - path: ./target/*-${nextRelease.version}.jar
          label: Artifact
        - path: ./target/*-${nextRelease.version}.sources.jar
          label: Sources
        - path: ./target/*-${nextRelease.version}-javadoc.jar
          label: Javadoc
      addReleases: top
