on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 17  # It is recommended to specify specifying version range
        # for semantic-release.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
