on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: |
          echo "GITHUB_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "Branche : $GITHUB_BRANCH"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Import GPG
        run: export GPG_TTY=$(tty) && echo -e "$GPG_PRIVATE_KEY" | gpg --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.gpg_private_key }}
      - name: Build artifact
        run: chmod +x mvnw && ./mvnw -B -ntp clean package
      - name: Semantic Prerelease
        if: env.GITHUB_BRANCH != 'main'
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.2.2
          branches: ${{ env.GITHUB_BRANCH }}
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git@9.0.0
            @semantic-release/exec@5.0.0
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Semantic Release
        if: env.GITHUB_BRANCH == 'main'
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.2.2
          branches: main
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git@9.0.0
            @semantic-release/exec@5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

